#!/bin/bash

lib/ldak.4.9 --reml data/reml/CobDiameterMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobDiameterMainEffect.txt > logs/ldak-CobDiameterMainEffect.log &
lib/ldak.4.9 --reml data/reml/CobDiameterSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobDiameterSlope.txt > logs/ldak-CobDiameterSlope.log &
lib/ldak.4.9 --reml data/reml/CobDiameterVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobDiameterVarE.txt > logs/ldak-CobDiameterVarE.log &
lib/ldak.4.9 --reml data/reml/CobWeightMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobWeightMainEffect.txt > logs/ldak-CobWeightMainEffect.log &
lib/ldak.4.9 --reml data/reml/CobWeightSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobWeightSlope.txt > logs/ldak-CobWeightSlope.log &
lib/ldak.4.9 --reml data/reml/CobWeightVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/CobWeightVarE.txt > logs/ldak-CobWeightVarE.log &
lib/ldak.4.9 --reml data/reml/DaystoSilkMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaystoSilkMainEffect.txt > logs/ldak-DaystoSilkMainEffect.log &
lib/ldak.4.9 --reml data/reml/DaystoSilkSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaystoSilkSlope.txt > logs/ldak-DaystoSilkSlope.log &
lib/ldak.4.9 --reml data/reml/DaystoSilkVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaystoSilkVarE.txt > logs/ldak-DaystoSilkVarE.log &
lib/ldak.4.9 --reml data/reml/DaysToTasselMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaysToTasselMainEffect.txt > logs/ldak-DaysToTasselMainEffect.log &
lib/ldak.4.9 --reml data/reml/DaysToTasselSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaysToTasselSlope.txt > logs/ldak-DaysToTasselSlope.log &
lib/ldak.4.9 --reml data/reml/DaysToTasselVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/DaysToTasselVarE.txt > logs/ldak-DaysToTasselVarE.log
lib/ldak.4.9 --reml data/reml/EarDiameterMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarDiameterMainEffect.txt > logs/ldak-EarDiameterMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarDiameterSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarDiameterSlope.txt > logs/ldak-EarDiameterSlope.log &
lib/ldak.4.9 --reml data/reml/EarDiameterVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarDiameterVarE.txt > logs/ldak-EarDiameterVarE.log &
lib/ldak.4.9 --reml data/reml/EarHeightMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarHeightMainEffect.txt > logs/ldak-EarHeightMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarHeightSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarHeightSlope.txt > logs/ldak-EarHeightSlope.log &
lib/ldak.4.9 --reml data/reml/EarHeightVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarHeightVarE.txt > logs/ldak-EarHeightVarE.log &
lib/ldak.4.9 --reml data/reml/EarLengthMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarLengthMainEffect.txt > logs/ldak-EarLengthMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarLengthSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarLengthSlope.txt > logs/ldak-EarLengthSlope.log &
lib/ldak.4.9 --reml data/reml/EarLengthVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarLengthVarE.txt > logs/ldak-EarLengthVarE.log &
lib/ldak.4.9 --reml data/reml/EarRankNumberMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRankNumberMainEffect.txt > logs/ldak-EarRankNumberMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarRankNumberSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRankNumberSlope.txt > logs/ldak-EarRankNumberSlope.log &
lib/ldak.4.9 --reml data/reml/EarRankNumberVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRankNumberVarE.txt > logs/ldak-EarRankNumberVarE.log
lib/ldak.4.9 --reml data/reml/EarRowNumberMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRowNumberMainEffect.txt > logs/ldak-EarRowNumberMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarRowNumberSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRowNumberSlope.txt > logs/ldak-EarRowNumberSlope.log &
lib/ldak.4.9 --reml data/reml/EarRowNumberVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarRowNumberVarE.txt > logs/ldak-EarRowNumberVarE.log &
lib/ldak.4.9 --reml data/reml/EarWeightMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarWeightMainEffect.txt > logs/ldak-EarWeightMainEffect.log &
lib/ldak.4.9 --reml data/reml/EarWeightSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarWeightSlope.txt > logs/ldak-EarWeightSlope.log &
lib/ldak.4.9 --reml data/reml/EarWeightVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/EarWeightVarE.txt > logs/ldak-EarWeightVarE.log &
lib/ldak.4.9 --reml data/reml/GDDAnthesisSilkingIntervalMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDAnthesisSilkingIntervalMainEffect.txt > logs/ldak-GDDAnthesisSilkingIntervalMainEffect.log &
lib/ldak.4.9 --reml data/reml/GDDAnthesisSilkingIntervalSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDAnthesisSilkingIntervalSlope.txt > logs/ldak-GDDAnthesisSilkingIntervalSlope.log &
lib/ldak.4.9 --reml data/reml/GDDAnthesisSilkingIntervalVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDAnthesisSilkingIntervalVarE.txt > logs/ldak-GDDAnthesisSilkingIntervalVarE.log &
lib/ldak.4.9 --reml data/reml/GDDDaystoSilkMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoSilkMainEffect.txt > logs/ldak-GDDDaystoSilkMainEffect.log &
lib/ldak.4.9 --reml data/reml/GDDDaystoSilkSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoSilkSlope.txt > logs/ldak-GDDDaystoSilkSlope.log &
lib/ldak.4.9 --reml data/reml/GDDDaystoSilkVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoSilkVarE.txt > logs/ldak-GDDDaystoSilkVarE.log
lib/ldak.4.9 --reml data/reml/GDDDaystoTasselMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoTasselMainEffect.txt > logs/ldak-GDDDaystoTasselMainEffect.log &
lib/ldak.4.9 --reml data/reml/GDDDaystoTasselSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoTasselSlope.txt > logs/ldak-GDDDaystoTasselSlope.log &
lib/ldak.4.9 --reml data/reml/GDDDaystoTasselVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/GDDDaystoTasselVarE.txt > logs/ldak-GDDDaystoTasselVarE.log &
lib/ldak.4.9 --reml data/reml/HeightAboveEarMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/HeightAboveEarMainEffect.txt > logs/ldak-HeightAboveEarMainEffect.log &
lib/ldak.4.9 --reml data/reml/HeightAboveEarSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/HeightAboveEarSlope.txt > logs/ldak-HeightAboveEarSlope.log &
lib/ldak.4.9 --reml data/reml/HeightAboveEarVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/HeightAboveEarVarE.txt > logs/ldak-HeightAboveEarVarE.log &
lib/ldak.4.9 --reml data/reml/KernelDepthMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/KernelDepthMainEffect.txt > logs/ldak-KernelDepthMainEffect.log &
lib/ldak.4.9 --reml data/reml/KernelDepthSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/KernelDepthSlope.txt > logs/ldak-KernelDepthSlope.log &
lib/ldak.4.9 --reml data/reml/KernelDepthVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/KernelDepthVarE.txt > logs/ldak-KernelDepthVarE.log &
lib/ldak.4.9 --reml data/reml/LeafLengthMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafLengthMainEffect.txt > logs/ldak-LeafLengthMainEffect.log &
lib/ldak.4.9 --reml data/reml/LeafLengthSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafLengthSlope.txt > logs/ldak-LeafLengthSlope.log &
lib/ldak.4.9 --reml data/reml/LeafLengthVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafLengthVarE.txt > logs/ldak-LeafLengthVarE.log
lib/ldak.4.9 --reml data/reml/LeafWidthMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafWidthMainEffect.txt > logs/ldak-LeafWidthMainEffect.log &
lib/ldak.4.9 --reml data/reml/LeafWidthSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafWidthSlope.txt > logs/ldak-LeafWidthSlope.log &
lib/ldak.4.9 --reml data/reml/LeafWidthVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/LeafWidthVarE.txt > logs/ldak-LeafWidthVarE.log &
lib/ldak.4.9 --reml data/reml/MiddleLeafAngleMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/MiddleLeafAngleMainEffect.txt > logs/ldak-MiddleLeafAngleMainEffect.log &
lib/ldak.4.9 --reml data/reml/MiddleLeafAngleSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/MiddleLeafAngleSlope.txt > logs/ldak-MiddleLeafAngleSlope.log &
lib/ldak.4.9 --reml data/reml/MiddleLeafAngleVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/MiddleLeafAngleVarE.txt > logs/ldak-MiddleLeafAngleVarE.log &
lib/ldak.4.9 --reml data/reml/PlantHeightMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/PlantHeightMainEffect.txt > logs/ldak-PlantHeightMainEffect.log &
lib/ldak.4.9 --reml data/reml/PlantHeightSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/PlantHeightSlope.txt > logs/ldak-PlantHeightSlope.log &
lib/ldak.4.9 --reml data/reml/PlantHeightVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/PlantHeightVarE.txt > logs/ldak-PlantHeightVarE.log &
lib/ldak.4.9 --reml data/reml/TasselLengthMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselLengthMainEffect.txt > logs/ldak-TasselLengthMainEffect.log &
lib/ldak.4.9 --reml data/reml/TasselLengthSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselLengthSlope.txt > logs/ldak-TasselLengthSlope.log &
lib/ldak.4.9 --reml data/reml/TasselLengthVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselLengthVarE.txt > logs/ldak-TasselLengthVarE.log
lib/ldak.4.9 --reml data/reml/TasselPrimaryBranchesMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselPrimaryBranchesMainEffect.txt > logs/ldak-TasselPrimaryBranchesMainEffect.log &
lib/ldak.4.9 --reml data/reml/TasselPrimaryBranchesSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselPrimaryBranchesSlope.txt > logs/ldak-TasselPrimaryBranchesSlope.log &
lib/ldak.4.9 --reml data/reml/TasselPrimaryBranchesVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TasselPrimaryBranchesVarE.txt > logs/ldak-TasselPrimaryBranchesVarE.log &
lib/ldak.4.9 --reml data/reml/TotalKernelVolumeMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TotalKernelVolumeMainEffect.txt > logs/ldak-TotalKernelVolumeMainEffect.log &
lib/ldak.4.9 --reml data/reml/TotalKernelVolumeSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TotalKernelVolumeSlope.txt > logs/ldak-TotalKernelVolumeSlope.log &
lib/ldak.4.9 --reml data/reml/TotalKernelVolumeVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/TotalKernelVolumeVarE.txt > logs/ldak-TotalKernelVolumeVarE.log &
lib/ldak.4.9 --reml data/reml/UpperLeafAngleMainEffect --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/UpperLeafAngleMainEffect.txt > logs/ldak-UpperLeafAngleMainEffect.log &
lib/ldak.4.9 --reml data/reml/UpperLeafAngleSlope --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/UpperLeafAngleSlope.txt > logs/ldak-UpperLeafAngleSlope.log &
lib/ldak.4.9 --reml data/reml/UpperLeafAngleVarE --mgrm data/kinship-matrices/multi_grm.txt --kinship-details NO --covar data/nam3pc.qcovar --pheno data/phenotypes/UpperLeafAngleVarE.txt > logs/ldak-UpperLeafAngleVarE.log &
